### ISSUE TITLE
Request: Make Background Color Optional

### ISSUE THREAD

**Issue by spyke01** [GuillaumeJasmin/react-table-hoc-fixed-columns#8]
Can we make the background color optional? Perhaps add a separate prop or just rely on the user making this additional change themselves?

**Comment by GuillaumeJasmin** [comment]
Background color of a row ?

**Comment by spyke01** [comment]
Sorry should have explained in more detail, the background color for the fixed elements appears to be hardcoded to white so that the fixed elements don't just overly on the other table column data when scrolling.

Instead of making this white it would be great to have the option of keeping these the default colors and then allowing the developer to specify otherwise if need by via CSS. Right now if you are keeping the default table styling you will have to do the following to get the table to convert back to the default style:

 ```scss
    .analytics .ReactTable .rt-thead, .analytics .ReactTable .rt-tfoot {
      .rt-th:first-child, .rt-td:first-child {
        background-color: #f5f7f8;
      }
    }

   .ReactTable.-striped .rt-tr {
      background: #fff;

      .rt-td:first-child {
        background: #fff !important;
      }
    }

    .ReactTable.-striped .rt-tr.-odd {
     /* Origina BGl is a translucent black overlay so I chose something close */
      background: #f9f9f9;

      .rt-td:first-child {
        background: #f9f9f9 !important;;
      }
    }
```
